#!/usr/bin/env python3
"""Build an Acorn DFS single-sided disc image (.ssd), or the sector table of one.

`build` writes the image: 80 tracks of 10 sectors, the catalogue in sectors 0 and 1, the
files from sector 2 on in the order given, boot option 3 (*EXEC !BOOT).  `table` writes the
ca65 include the game's loader reads the files by -- F_<name>_SEC and F_<name>_N, the first
sector and the sector count of each -- laying the files out exactly as `build` does, so the
two agree.  A file name may carry a DFS directory ('D.NAME'); in the table '!' becomes
'BOOT' and a '$.' directory is dropped from the symbol.

Usage:
    python3 tools/mkdfs.py build out.ssd title name:path[:load[:exec]] ...
    python3 tools/mkdfs.py table files.inc name:path ...
(build.sh runs both, from the game's directory; load and exec are hex, exec defaults to load.)
"""
import sys, struct

def build(out, title, files, boot=3):
    """Write the image: files is a list of (name, data, load, exec).  The catalogue lists the
    files by descending start sector, as DFS does; at most 31 files, and the files must fit
    the 800 sectors."""
    sectors = 800
    cat0 = bytearray(256)
    cat1 = bytearray(256)
    cat0[0:8] = title[:8].ljust(8).encode()
    cat1[0:4] = title[8:12].ljust(4).encode()
    # the catalogue's cycle number, the entry count * 8, the boot option with the sector
    # count's high bits, the sector count's low byte
    cat1[4] = 1
    cat1[5] = len(files) * 8
    cat1[6] = ((boot & 3) << 4) | ((sectors >> 8) & 3)
    cat1[7] = sectors & 255
    img = bytearray(sectors * 256)
    entries = []
    sec = 2
    for (name, data, load, exe) in files:
        start = sec
        nsec = (len(data) + 255) // 256
        img[start * 256:start * 256 + len(data)] = data
        sec += nsec
        entries.append((name, load, exe, len(data), start))
    assert sec <= sectors, 'disc full (%d sectors)' % sec
    assert len(files) <= 31, 'a DFS catalogue holds 31 files'
    entries.sort(key=lambda e: -e[4])
    for i, (name, load, exe, length, start) in enumerate(entries):
        d = '$'
        if '.' in name:
            d, name = name.split('.', 1)
        o = 8 + i * 8
        cat0[o:o + 7] = name[:7].ljust(7).encode()
        cat0[o + 7] = ord(d)
        cat1[o] = load & 255
        cat1[o + 1] = (load >> 8) & 255
        cat1[o + 2] = exe & 255
        cat1[o + 3] = (exe >> 8) & 255
        cat1[o + 4] = length & 255
        cat1[o + 5] = (length >> 8) & 255
        # the mixed byte: bits 17-16 of exec, length and load, and bits 9-8 of the start sector
        cat1[o + 6] = (((exe >> 16) & 3) << 6) | (((length >> 16) & 3) << 4) | (((load >> 16) & 3) << 2) | ((start >> 8) & 3)
        cat1[o + 7] = start & 255
    img[0:256] = cat0
    img[256:512] = cat1
    open(out, 'wb').write(img)

def layout(files):
    """{name: (start sector, sector count)} for the files, allocated as build() allocates
    them: from sector 2, in order, whole sectors each."""
    sec = 2
    res = {}
    for (name, data, load, exe) in files:
        nsec = (len(data) + 255) // 256
        res[name] = (sec, nsec)
        sec += nsec
    return res

if __name__ == '__main__':
    if len(sys.argv) < 3 or sys.argv[1] not in ('table', 'build'):
        sys.exit(__doc__)
    mode = sys.argv[1]
    if mode == 'table':
        out = sys.argv[2]
        files = []
        for spec in sys.argv[3:]:
            parts = spec.split(':')
            files.append((parts[0], open(parts[1], 'rb').read(), 0, 0))
        lay = layout(files)
        with open(out, 'w') as f:
            f.write('; generated by mkdfs.py table\n')
            for (name, data, load, exe) in files:
                sec, n = lay[name]
                ident = name.replace('!', 'BOOT').replace('$.', '')
                f.write('F_%s_SEC = %d\nF_%s_N = %d\n' % (ident, sec, ident, n))
        sys.exit(0)
    out, title = sys.argv[2], sys.argv[3]
    files = []
    for spec in sys.argv[4:]:
        parts = spec.split(':')
        name, path = parts[0], parts[1]
        load = int(parts[2], 16) if len(parts) > 2 else 0
        exe = int(parts[3], 16) if len(parts) > 3 else load
        files.append((name, open(path, 'rb').read(), load, exe))
    build(out, title, files)
